import { AlertCircle } from "lucide-react";

export function DemoBadge() {
  return (
    <div className="rounded-lg border border-amber-500/20 bg-amber-500/5 p-3 flex items-center gap-2.5">
      <AlertCircle className="h-4 w-4 text-amber-400 shrink-0" />
      <div>
        <p className="text-xs font-medium text-amber-400">Demo Analysis</p>
        <p className="text-[11px] text-muted-foreground">
          This result was generated by TruthLens&apos;s demo analysis engine. Connect an
          AI provider for real-world verification.
        </p>
      </div>
    </div>
  );
}
